package com.banco.cadastro.br.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ArqMetadataAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArqMetadataAllPropertiesEquals(ArqMetadata expected, ArqMetadata actual) {
        assertArqMetadataAutoGeneratedPropertiesEquals(expected, actual);
        assertArqMetadataAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArqMetadataAllUpdatablePropertiesEquals(ArqMetadata expected, ArqMetadata actual) {
        assertArqMetadataUpdatableFieldsEquals(expected, actual);
        assertArqMetadataUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArqMetadataAutoGeneratedPropertiesEquals(ArqMetadata expected, ArqMetadata actual) {
        assertThat(actual)
            .as("Verify ArqMetadata auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArqMetadataUpdatableFieldsEquals(ArqMetadata expected, ArqMetadata actual) {
        assertThat(actual)
            .as("Verify ArqMetadata relevant properties")
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getObs()).as("check obs").isEqualTo(expected.getObs()))
            .satisfies(a ->
                assertThat(a.getArquivoContentType()).as("check arquivo contenty type").isEqualTo(expected.getArquivoContentType())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArqMetadataUpdatableRelationshipsEquals(ArqMetadata expected, ArqMetadata actual) {
        // empty method
    }
}
