package com.banco.cadastro.br.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ArquivoByteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArquivoByteAllPropertiesEquals(ArquivoByte expected, ArquivoByte actual) {
        assertArquivoByteAutoGeneratedPropertiesEquals(expected, actual);
        assertArquivoByteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArquivoByteAllUpdatablePropertiesEquals(ArquivoByte expected, ArquivoByte actual) {
        assertArquivoByteUpdatableFieldsEquals(expected, actual);
        assertArquivoByteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArquivoByteAutoGeneratedPropertiesEquals(ArquivoByte expected, ArquivoByte actual) {
        assertThat(actual)
            .as("Verify ArquivoByte auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArquivoByteUpdatableFieldsEquals(ArquivoByte expected, ArquivoByte actual) {
        assertThat(actual)
            .as("Verify ArquivoByte relevant properties")
            .satisfies(a -> assertThat(a.getArquivo()).as("check arquivo").isEqualTo(expected.getArquivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArquivoByteUpdatableRelationshipsEquals(ArquivoByte expected, ArquivoByte actual) {
        assertThat(actual)
            .as("Verify ArquivoByte relationships")
            .satisfies(a -> assertThat(a.getArqMetadata()).as("check arqMetadata").isEqualTo(expected.getArqMetadata()));
    }
}
