package com.banco.cadastro.br.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClassePadraoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassePadraoAllPropertiesEquals(ClassePadrao expected, ClassePadrao actual) {
        assertClassePadraoAutoGeneratedPropertiesEquals(expected, actual);
        assertClassePadraoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassePadraoAllUpdatablePropertiesEquals(ClassePadrao expected, ClassePadrao actual) {
        assertClassePadraoUpdatableFieldsEquals(expected, actual);
        assertClassePadraoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassePadraoAutoGeneratedPropertiesEquals(ClassePadrao expected, ClassePadrao actual) {
        assertThat(actual)
            .as("Verify ClassePadrao auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassePadraoUpdatableFieldsEquals(ClassePadrao expected, ClassePadrao actual) {
        assertThat(actual)
            .as("Verify ClassePadrao relevant properties")
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getDescricao()).as("check descricao").isEqualTo(expected.getDescricao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassePadraoUpdatableRelationshipsEquals(ClassePadrao expected, ClassePadrao actual) {
        // empty method
    }
}
