package com.banco.cadastro.br.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DadoPadraoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDadoPadraoAllPropertiesEquals(DadoPadrao expected, DadoPadrao actual) {
        assertDadoPadraoAutoGeneratedPropertiesEquals(expected, actual);
        assertDadoPadraoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDadoPadraoAllUpdatablePropertiesEquals(DadoPadrao expected, DadoPadrao actual) {
        assertDadoPadraoUpdatableFieldsEquals(expected, actual);
        assertDadoPadraoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDadoPadraoAutoGeneratedPropertiesEquals(DadoPadrao expected, DadoPadrao actual) {
        assertThat(actual)
            .as("Verify DadoPadrao auto generated properties")
            .satisfies(a -> assertThat(a.getId().getClassePadraoId()).as("check ClassePadraoId").isEqualTo(expected.getId().getClassePadraoId()))
            .satisfies(a -> assertThat(a.getId().getIdDado()).as("check IdDado").isEqualTo(expected.getId().getIdDado()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDadoPadraoUpdatableFieldsEquals(DadoPadrao expected, DadoPadrao actual) {
        assertThat(actual)
            .as("Verify DadoPadrao relevant properties")
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getDescricao()).as("check descricao").isEqualTo(expected.getDescricao()))
            .satisfies(a -> assertThat(a.getAtivo()).as("check ativo").isEqualTo(expected.getAtivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDadoPadraoUpdatableRelationshipsEquals(DadoPadrao expected, DadoPadrao actual) {
        assertThat(actual)
            .as("Verify DadoPadrao relationships")
            .satisfies(a -> assertThat(a.getClassePadrao()).as("check classePadrao").isEqualTo(expected.getClassePadrao()));
    }
}
