INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo, idDadoDependencia, classePadraoIdDependencia) VALUES(1 , 8, 'Acre', 'AC', 1, 1, 7);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo, idDadoDependencia, classePadraoIdDependencia) VALUES(2 , 8, 'Alagoas', 'AL', 1, 1, 7);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo, idDadoDependencia, classePadraoIdDependencia) VALUES(3 , 8, 'Amazonas', 'AM', 1, 1, 7);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo, idDadoDependencia, classePadraoIdDependencia) VALUES(4 , 8, 'Amapá', 'AP', 1, 1, 7);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo, idDadoDependencia, classePadraoIdDependencia) VALUES(5 , 8, 'Bahia', 'BA', 1, 1, 7);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo, idDadoDependencia, classePadraoIdDependencia) VALUES(6 , 8, 'Ceará', 'CE', 1, 1, 7);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo, idDadoDependencia, classePadraoIdDependencia) VALUES(7 , 8, 'Distrito Federal', 'DF', 1, 1, 7);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo, idDadoDependencia, classePadraoIdDependencia) VALUES(8 , 8, 'Espírito Santo', 'ES', 1, 1, 7);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo, idDadoDependencia, classePadraoIdDependencia) VALUES(9 , 8, 'Goiás', 'GO', 1, 1, 7);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo, idDadoDependencia, classePadraoIdDependencia) VALUES(10, 8, 'Maranhão', 'MA', 1, 1, 7);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo, idDadoDependencia, classePadraoIdDependencia) VALUES(11, 8, 'Minas Gerais', 'MG', 1, 1, 7);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo, idDadoDependencia, classePadraoIdDependencia) VALUES(12, 8, 'Mato Grosso do Sul', 'MS', 1, 1, 7);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo, idDadoDependencia, classePadraoIdDependencia) VALUES(13, 8, 'Mato Grosso', 'MT', 1, 1, 7);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo, idDadoDependencia, classePadraoIdDependencia) VALUES(14, 8, 'Pará', 'PA', 1, 1, 7);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo, idDadoDependencia, classePadraoIdDependencia) VALUES(15, 8, 'Paraíba', 'PB', 1, 1, 7);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo, idDadoDependencia, classePadraoIdDependencia) VALUES(16, 8, 'Pernambuco', 'PE', 1, 1, 7);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo, idDadoDependencia, classePadraoIdDependencia) VALUES(17, 8, 'Piauí', 'PI', 1, 1, 7);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo, idDadoDependencia, classePadraoIdDependencia) VALUES(18, 8, 'Paraná', 'PR', 1, 1, 7);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo, idDadoDependencia, classePadraoIdDependencia) VALUES(19, 8, 'Rio de Janeiro', 'RJ', 1, 1, 7);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo, idDadoDependencia, classePadraoIdDependencia) VALUES(20, 8, 'Rio Grande do Norte', 'RN', 1, 1, 7);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo, idDadoDependencia, classePadraoIdDependencia) VALUES(21, 8, 'Rondônia', 'RO', 1, 1, 7);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo, idDadoDependencia, classePadraoIdDependencia) VALUES(22, 8, 'Roraima', 'RR', 1, 1, 7);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo, idDadoDependencia, classePadraoIdDependencia) VALUES(23, 8, 'Rio Grande do Sul', 'RS', 1, 1, 7);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo, idDadoDependencia, classePadraoIdDependencia) VALUES(24, 8, 'Santa Catarina', 'SC', 1, 1, 7);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo, idDadoDependencia, classePadraoIdDependencia) VALUES(25, 8, 'Sergipe', 'SE', 1, 1, 7);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo, idDadoDependencia, classePadraoIdDependencia) VALUES(26, 8, 'São Paulo', 'SP', 1, 1, 7);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo, idDadoDependencia, classePadraoIdDependencia) VALUES(27, 8, 'Tocantins', 'TO', 1, 1, 7);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo, idDadoDependencia, classePadraoIdDependencia) VALUES(99, 8, 'Exterior', 'EX', 1, 1, 7);
