INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (1  , 7, 'Brazil', 'Brasil', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (2  , 7, 'Afghanistan', 'Afeganistão', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (3  , 7, 'Albania', 'Albânia, Republica da', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (4  , 7, 'Algeria', 'Argélia', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (5  , 7, 'American Samoa', 'Samoa Americana', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (6  , 7, 'Andorra', 'Andorra', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (7  , 7, 'Angola', 'Angola', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (8  , 7, 'Anguilla', 'Anguilla', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (9  , 7, 'Antarctica', 'Antártida', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (10 , 7, 'Antigua and Barbuda', 'Antigua e Barbuda', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (11 , 7, 'Argentina', 'Argentina', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (12 , 7, 'Armenia', 'Armênia, Republica da', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (13 , 7, 'Aruba', 'Aruba', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (14 , 7, 'Australia', 'Austrália', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (15 , 7, 'Austria', 'Áustria', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (16 , 7, 'Azerbaijan', 'Azerbaijão, Republica do', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (17 , 7, 'Bahamas', 'Bahamas, Ilhas',1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (18 , 7, 'Bahrain', 'Bahrein, Ilhas',1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (19 , 7, 'Bangladesh', 'Bangladesh',1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (20 , 7, 'Barbados', 'Barbados',1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (21 , 7, 'Belarus', 'Belarus, Republica da',1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (22 , 7, 'Belgium', 'Bélgica',1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (23 , 7, 'Belize', 'Belize',1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (24 , 7, 'Benin', 'Benin', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (25 , 7, 'Bermuda', 'Bermudas',1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (26 , 7, 'Bhutan', 'Butão', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (27 , 7, 'Bolivia', 'Bolívia',1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (28 , 7, 'Bosnia and Herzegowina', 'Bósnia-herzegovina (Republica da)',1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (29 , 7, 'Botswana', 'Botsuana', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (30 , 7, 'Bouvet Island', 'Bouvet, Ilha', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (31 , 7, 'British Indian Ocean Territory', 'Território Britânico do Oceano Indico', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (32 , 7, 'Brunei Darussalam', 'Brunei', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (33 , 7, 'Bulgaria', 'Bulgária, Republica da', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (34 , 7, 'Burkina Faso', 'Burkina Faso',1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (35 , 7, 'Burundi', 'Burundi', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (36 , 7, 'Cambodia', 'Camboja', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (37 , 7, 'Cameroon', 'Camarões', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (38 , 7, 'Canada', 'Canada', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (39 , 7, 'Cape Verde', 'Cabo Verde, Republica de', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (40 , 7, 'Cayman Islands', 'Cayman, Ilhas', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (41 , 7, 'Central African Republic', 'Republica Centro-Africana', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (42 , 7, 'Chad', 'Chade', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (43 , 7, 'Chile', 'Chile', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (44 , 7, 'China', 'China, Republica Popular', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (45 , 7, 'Christmas Island', 'Christmas, Ilha (Navidad)', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (46 , 7, 'Cocos (Keeling) Islands', 'Cocos (Keeling), Ilhas', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (47 , 7, 'Colombia', 'Colômbia', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (48 , 7, 'Comoros', 'Comores, Ilhas', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (49 , 7, 'Congo', 'Congo', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (50 , 7, 'Congo, the Democratic Republic of the', 'Congo, Republica Democrática do', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (51 , 7, 'Cook Islands', 'Cook, Ilhas', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (52 , 7, 'Costa Rica', 'Costa Rica', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (53 , 7, 'Cote d`Ivoire', 'Costa do Marfim', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (54 , 7, 'Croatia (Hrvatska)', 'Croácia (Republica da)', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (55 , 7, 'Cuba', 'Cuba', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (56 , 7, 'Cyprus', 'Chipre', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (57 , 7, 'Czech Republic', 'Tcheca, Republica', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (58 , 7, 'Denmark', 'Dinamarca', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (59 , 7, 'Djibouti', 'Djibuti', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (60 , 7, 'Dominica', 'Dominica, Ilha', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (61 , 7, 'Dominican Republic', 'Republica Dominicana', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (62 , 7, 'East Timor', 'Timor Leste', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (63 , 7, 'Ecuador', 'Equador', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (64 , 7, 'Egypt', 'Egito', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (65 , 7, 'El Salvador', 'El Salvador', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (66 , 7, 'Equatorial Guinea', 'Guine-Equatorial', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (67 , 7, 'Eritrea', 'Eritreia', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (68 , 7, 'Estonia', 'Estônia, Republica da', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (69 , 7, 'Ethiopia', 'Etiópia', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (70 , 7, 'Falkland Islands (Malvinas)', 'Falkland (Ilhas Malvinas)', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (71 , 7, 'Faroe Islands', 'Feroe, Ilhas', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (72 , 7, 'Fiji', 'Fiji', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (73 , 7, 'Finland', 'Finlândia', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (74 , 7, 'France', 'Franca', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (76 , 7, 'French Guiana', 'Guiana francesa', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (77 , 7, 'French Polynesia', 'Polinésia Francesa', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (78 , 7, 'French Southern Territories', 'Terras Austrais e Antárticas Francesas', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (79 , 7, 'Gabon', 'Gabão', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (80 , 7, 'Gambia', 'Gambia', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (81 , 7, 'Georgia', 'Georgia, Republica da', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (82 , 7, 'Germany', 'Alemanha',1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (83 , 7, 'Ghana', 'Gana', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (84 , 7, 'Gibraltar', 'Gibraltar', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (85 , 7, 'Greece', 'Grécia', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (86 , 7, 'Greenland', 'Groenlândia', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (87 , 7, 'Grenada', 'Granada', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (88 , 7, 'Guadeloupe', 'Guadalupe', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (89 , 7, 'Guam', 'Guam', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (90 , 7, 'Guatemala', 'Guatemala', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (91 , 7, 'Guinea', 'Guine', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (92 , 7, 'Guinea-Bissau', 'Guine-Bissau', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (93 , 7, 'Guyana', 'Guiana', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (94 , 7, 'Haiti', 'Haiti', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (95 , 7, 'Heard and Mc Donald Islands', 'Ilha Heard e Ilhas McDonald', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (96 , 7, 'Holy See (Vatican City State)', 'Vaticano, Estado da Cidade do', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (97 , 7, 'Honduras', 'Honduras', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (98 , 7, 'Hong Kong', 'Hong Kong', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (99 , 7, 'Hungary', 'Hungria, Republica da', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (100, 7, 'Iceland', 'Islândia', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (101, 7, 'India', 'Índia', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (102, 7, 'Indonesia', 'Indonésia', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (103, 7, 'Iran (Islamic Republic of)', 'Ira, Republica Islâmica do', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (104, 7, 'Iraq', 'Iraque', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (105, 7, 'Ireland', 'Irlanda', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (106, 7, 'Israel', 'Israel', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (107, 7, 'Italy', 'Itália', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (108, 7, 'Jamaica', 'Jamaica', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (109, 7, 'Japan', 'Japão', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (110, 7, 'Jordan', 'Jordânia', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (111, 7, 'Kazakhstan', 'Cazaquistão, Republica do', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (112, 7, 'Kenya', 'Quênia', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (113, 7, 'Kiribati', 'Kiribati', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (114, 7, 'Korea, Democratic People`s Republic of', 'Coreia, Republica Popular Democrática da', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (115, 7, 'Korea, Republic of', 'Coreia, Republica da', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (116, 7, 'Kuwait', 'Kuwait', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (117, 7, 'Kyrgyzstan', 'Quirguiz, Republica', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (118, 7, 'Lao People`s Democratic Republic', 'Laos, Republica Popular Democrática do', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (119, 7, 'Latvia', 'Letônia, Republica da', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (120, 7, 'Lebanon', 'Líbano', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (121, 7, 'Lesotho', 'Lesoto', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (122, 7, 'Liberia', 'Libéria', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (123, 7, 'Libyan Arab Jamahiriya', 'Líbia', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (124, 7, 'Liechtenstein', 'Liechtenstein', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (125, 7, 'Lithuania', 'Lituânia, Republica da', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (126, 7, 'Luxembourg', 'Luxemburgo', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (127, 7, 'Macau', 'Macau', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (128, 7, 'North Macedonia', 'Macedônia do Norte', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (129, 7, 'Madagascar', 'Madagascar', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (130, 7, 'Malawi', 'Malavi', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (131, 7, 'Malaysia', 'Malásia', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (132, 7, 'Maldives', 'Maldivas', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (133, 7, 'Mali', 'Mali', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (134, 7, 'Malta', 'Malta', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (135, 7, 'Marshall Islands', 'Marshall, Ilhas', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (136, 7, 'Martinique', 'Martinica', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (137, 7, 'Mauritania', 'Mauritânia', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (138, 7, 'Mauritius', 'Mauricio', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (139, 7, 'Mayotte', 'Mayotte (Ilhas Francesas)', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (140, 7, 'Mexico', 'México', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (141, 7, 'Micronesia, Federated States of', 'Micronesia', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (142, 7, 'Moldova, Republic of', 'Moldávia, Republica da', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (143, 7, 'Monaco', 'Mônaco', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (144, 7, 'Mongolia', 'Mongólia', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (145, 7, 'Montserrat', 'Montserrat, Ilhas', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (146, 7, 'Morocco', 'Marrocos', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (147, 7, 'Mozambique', 'Moçambique', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (148, 7, 'Myanmar', 'Mianmar (Birmânia)',1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (149, 7, 'Namibia', 'Namíbia', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (150, 7, 'Nauru', 'Nauru', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (151, 7, 'Nepal', 'Nepal', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (152, 7, 'Netherlands', 'Países Baixos (Holanda)', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (154, 7, 'New Caledonia', 'Nova Caledonia', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (155, 7, 'New Zealand', 'Nova Zelândia', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (156, 7, 'Nicaragua', 'Nicarágua', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (157, 7, 'Niger', 'Níger', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (158, 7, 'Nigeria', 'Nigéria', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (159, 7, 'Niue', 'Niue, Ilha', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (160, 7, 'Norfolk Island', 'Norfolk, Ilha', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (161, 7, 'Northern Mariana Islands', 'Marianas do Norte', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (162, 7, 'Norway', 'Noruega', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (163, 7, 'Oman', 'Oma', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (164, 7, 'Pakistan', 'Paquistão', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (165, 7, 'Palau', 'Palau', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (166, 7, 'Panama', 'Panamá', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (167, 7, 'Papua New Guinea', 'Papua Nova Guine', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (168, 7, 'Paraguay', 'Paraguai', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (169, 7, 'Peru', 'Peru', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (170, 7, 'Philippines', 'Filipinas', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (171, 7, 'Pitcairn', 'Pitcairn, Ilha', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (172, 7, 'Poland', 'Polônia, Republica da', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (173, 7, 'Portugal', 'Portugal', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (174, 7, 'Puerto Rico', 'Porto Rico', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (175, 7, 'Qatar', 'Catar', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (176, 7, 'Reunion', 'Reunião, Ilha', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (177, 7, 'Romania', 'Romênia', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (178, 7, 'Russian Federation', 'Rússia, Federação da', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (179, 7, 'Rwanda', 'Ruanda', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (180, 7, 'Saint Kitts and Nevis', 'São Cristovão e Neves, Ilhas', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (181, 7, 'Saint LUCIA', 'Santa Lucia', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (182, 7, 'Saint Vincent and the Grenadines', 'São Vicente e Granadinas', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (183, 7, 'Samoa', 'Samoa', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (184, 7, 'San Marino', 'San Marino', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (185, 7, 'Sao Tome and Principe', 'São Tome e Príncipe, Ilhas', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (186, 7, 'Saudi Arabia', 'Arábia Saudita',1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (187, 7, 'Senegal', 'Senegal', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (188, 7, 'Seychelles', 'Seychelles', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (189, 7, 'Sierra Leone', 'Serra Leoa', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (190, 7, 'Singapore', 'Cingapura', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (191, 7, 'Slovakia (Slovak Republic)', 'Eslovaca, Republica', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (192, 7, 'Slovenia', 'Eslovênia, Republica da', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (193, 7, 'Solomon Islands', 'Salomão, Ilhas', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (194, 7, 'Somalia', 'Somalia', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (195, 7, 'South Africa', 'África do Sul', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (196, 7, 'South Georgia and the South Sandwich Islands', 'Ilhas Geórgia do Sul e Sandwich do Sul', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (197, 7, 'Spain', 'Espanha', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (198, 7, 'Sri Lanka', 'Sri Lanka', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (199, 7, 'St. Helena', 'Santa Helena', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (200, 7, 'St. Pierre and Miquelon', 'São Pedro e Miquelon', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (201, 7, 'Sudan', 'Sudão', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (202, 7, 'Suriname', 'Suriname', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (203, 7, 'Svalbard and Jan Mayen Islands', 'Svalbard e Jan Mayen', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (204, 7, 'Swaziland', 'Eswatini', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (205, 7, 'Sweden', 'Suécia', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (206, 7, 'Switzerland', 'Suíça', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (207, 7, 'Syrian Arab Republic', 'Síria, Republica Árabe da', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (208, 7, 'Taiwan, Province of China', 'Formosa (Taiwan)', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (209, 7, 'Tajikistan', 'Tadjiquistao, Republica do', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (210, 7, 'Tanzania, United Republic of', 'Tanzânia, Republica Unida da', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (211, 7, 'Thailand', 'Tailândia', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (212, 7, 'Togo', 'Togo', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (213, 7, 'Tokelau', 'Toquelau, Ilhas', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (214, 7, 'Tonga', 'Tonga', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (215, 7, 'Trinidad and Tobago', 'Trinidad e Tobago', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (216, 7, 'Tunisia', 'Tunísia', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (217, 7, 'Turkey', 'Turquia', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (218, 7, 'Turkmenistan', 'Turcomenistão, Republica do', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (219, 7, 'Turks and Caicos Islands', 'Turcas e Caicos, Ilhas', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (220, 7, 'Tuvalu', 'Tuvalu', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (221, 7, 'Uganda', 'Uganda', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (222, 7, 'Ukraine', 'Ucrânia', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (223, 7, 'United Arab Emirates', 'Emirados Árabes Unidos', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (224, 7, 'United Kingdom', 'Reino Unido', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (225, 7, 'United States', 'Estados Unidos', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (226, 7, 'United States Minor Outlying Islands', 'Ilhas Menores Distantes dos Estados Unidos', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (227, 7, 'Uruguay', 'Uruguai', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (228, 7, 'Uzbekistan', 'Uzbequistão, Republica do', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (229, 7, 'Vanuatu', 'Vanuatu', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (230, 7, 'Venezuela', 'Venezuela', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (231, 7, 'Viet Nam', 'Vietnã', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (232, 7, 'Virgin Islands (British)', 'Virgens, Ilhas (Britânicas)', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (233, 7, 'Virgin Islands (U.S.)', 'Virgens, Ilhas (E.U.A.)', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (234, 7, 'Wallis and Futuna Islands', 'Wallis e Futuna, Ilhas', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (235, 7, 'Western Sahara', 'Saara Ocidental', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (236, 7, 'Yemen', 'Iémen', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (237, 7, 'Yugoslavia', 'Iugoslávia, República Fed. da', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (238, 7, 'Zambia', 'Zâmbia', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (239, 7, 'Zimbabwe', 'Zimbabue', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (240, 7, 'Bailiwick of Guernsey', 'Guernsey, Ilha do Canal (Inclui Alderney e Sark)', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (241, 7, 'Bailiwick of Jersey', 'Jersey, Ilha do Canal', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (243, 7, 'Isle of Man', 'Man, Ilha de', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (246, 7, 'Crna Gora (Montenegro)', 'Montenegro', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (247, 7, 'SÉRVIA', 'Republika Srbija', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (248, 7, 'Republic of South Sudan', 'Sudao do Sul', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (249, 7, 'Zona del Canal de Panamá', 'Zona do Canal do Panamá', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (252, 7, 'Dawlat Filasṭīn', 'Palestina', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (253, 7, 'Åland Islands', 'Aland, Ilhas',1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (255, 7, 'Curaçao', 'Curaçao',1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (256, 7, 'Saint Martin', 'São Martinho, Ilha de (Parte Holandesa)', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (258, 7, 'Bonaire', 'Bonaire',1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (259, 7, 'Antartica', 'Antartica',1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (260, 7, 'Heard Island and McDonald Islands', 'Ilha Herad e Ilhas Macdonald', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (261, 7, 'Saint-Barthélemy', 'São Bartolomeu', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (262, 7, 'Saint Martin', 'São Martinho, Ilha de (Parte Francesa)', 1);
INSERT INTO dycad_dadopadrao(idDado, classePadraoId, nome, descricao, ativo) VALUES (263, 7, 'Terres Australes et Antarctiques Françaises', 'Terras Austrais e Antárcticas Francesas', 1);
